### ISSUE TITLE
build failure of  0.7.8.0 with ghc 8

### ISSUE THREAD

**Issue by cartazio** [mchakravarty/language-c-inline#55]
some constructors changed :) 

```
Language/C/Inline/Hint.hs:87:9: error:
    • The constructor ‘ClassOpI’ should have 3 arguments, but has been given 4
    • In the pattern: ClassOpI _ ty _ _
      In a case alternative: ClassOpI _ ty _ _ -> return ty
      In a stmt of a 'do' block:
        case info of {
          ClassOpI _ ty _ _ -> return ty
          VarI _ ty _ _ -> return ty
          nonVarInfo
            -> do { reportErrorAndFail ObjC
                    $ "expected '"
                      ++
                        show name
                        ++
                          "' to be a typed variable name, but it is "
                          ++ show (ppr nonVarInfo) } }
cabal: Leaving directory '/var/folders/py/wgp_hj9d2rl3cx48yym_ynj00000gn/T/cabal-tmp-20250/language-c-inline-0.7.8.0'
cabal: Error: some packages failed to install:
language-c-inline-0.7.8.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by yairchu** [comment]
I've recently needed to make some ObjC calls and looked at this package and found it bitrot (doesn't build with GHC 9.2.7).

Is it worth reviving? If so I suppose I could perhaps give it a try.
Otherwise, so far I went with adding very basic ObjC support to the `inline-c` family of packages, see https://github.com/fpco/inline-c/pull/143

**Comment by mchakravarty** [comment]
Yes, sorry, unfortunately, I didn't have the time to maintain the package. There are also comments in https://github.com/mchakravarty/language-c-inline/tree/release/0.7 that have not been merged with main.

`inline-c` has a quite different feature set. Depends on what you need.
